[05/05/2018 21:08] ERROR blue <module> 606: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "blue.py", line 586, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Program Files\Python36\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "blue.py", line 568, in main
    bot.user.setUsername("Mono5_FullHope")
AttributeError: 'NoneType' object has no attribute 'setUsername'
[05/05/2018 21:16] ERROR blue <module> 606: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "blue.py", line 586, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Program Files\Python36\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "blue.py", line 568, in main
    bot.user.setUsername("Mono5_FullHope")
AttributeError: 'NoneType' object has no attribute 'setUsername'
[05/05/2018 23:08] INFO economy _set 391: Mono5_Max(420311027255607316) set 50000 credits to Mono5_Max (420311027255607316)
